name: gcc-x86_64_toolchain
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  build_mpv:
    name: Building mpv
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:  
      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main
        with:
          ref: master

      - name: Loading gcc-x86_64_v3 toolchain cache
        uses: actions/cache/restore@main
        with:
          path: |
            build_x86_64_v3
          key: ${{ secrets.CACHE_VERSION }}-gcc-x86_64_v3_toolchain-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-gcc-x86_64_v3_toolchain

      - name: Get clang_root cache
        run: |
          7z a gcc-build_x86_64_v3.7z build_x86_64_v3/*
          
      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@master
        with:
          tag_name: toolchain
          name: toolchain
          files: gcc*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
